### ISSUE TITLE
Express & Middleware

### ISSUE THREAD

**Issue by CrabDude** [codepath/nodejs_guides#12]
Express
- Express hello world (links to corresponding [express docs](http://expressjs.com/starter/hello-world.html))
- routing examples (links to corresponding express docs)
- Rendering example (using ejs)
- encourage route & middleware modularization:

**Route example**

``` node
function getUsers(req, res, next) {
  // ...
}

function createUser(req, res, next) {
  // ...
}

module.exports = (app)=> {
  app.get('/users', getUsers)
  app.put('/user', createUser)
}
```

**Middleware example**

``` node
module.exports = (req, res, next) => {
  req.someProperty = true
  next()
}
```

Middleware
- `app.use`, ordering, function signature (`(req, res, next) => {}`)
- in Express 4, routes are in the order they're added relative to other middleware
  - Show an example of 2 routes with the body-parser middleware in the stack between them
  - Point out how the first route can be used for streaming (no body parser) while latter will have `req.body`
- route middleware, encourage reusability & composability
- common middleware

**What success looks like: Succinctness and clarity. Less is more.**
Reference Wikis: [Authentication & Authorization](https://github.com/codepath/nodejs_guides/wiki/Authorization-&-Authentication), [Setup](https://github.com/codepath/nodejs_guides/wiki/Setup)

Open separate issues for required links to community sources if you're having trouble finding any.

_Please assign to yourself before working on this._
/cc @NinjaSudo @philster @azoff @DiyahM

**Comment by CrabDude** [comment]
ETA?

**Comment by psvet** [comment]
https://github.com/codepath/nodejs_guides/wiki/Express-&-Middleware

Really sorry Adam, this past week was unexpectedly heavy. I just finished my write-up and noticed you had already included some info in the guide, so I integrated yours into mine. This delay won't happen again.

**Comment by CrabDude** [comment]
This looks really good. I'll go through it with a fine-tooth comb more later, but I think you've nailed the broad strokes.
