### ISSUE TITLE
Filesystem

### ISSUE THREAD

**Issue by CrabDude** [codepath/nodejs_guides#13]
- file CRUD examples with streaming versions of CRU
- stat example, especially isDirectory
- fs.watch & [chokidar](https://www.npmjs.com/package/chokidar) examples
- Explain that there are Sync versions of everything that should **ONLY BE USED** on the first eventloop tick
- Show examples using songbird's promises
- Mention [fs-extra](https://www.npmjs.com/package/fs-extra)

**What success looks like: Succinctness and clarity. Less is more.**
Reference Wikis: [Authentication & Authorization](https://github.com/codepath/nodejs_guides/wiki/Authorization-&-Authentication), [Setup](https://github.com/codepath/nodejs_guides/wiki/Setup)

Open separate issues for required links to community sources if you're having trouble finding any.

_Please assign to yourself before working on this._
/cc @NinjaSudo @philster @azoff @DiyahM

**Comment by psvet** [comment]
https://github.com/codepath/nodejs_guides/wiki/Filesystem

Still working on this one, but just wanted to share how it's going. It's definitely more bare-bones than the last one, so let me know if you want anything more fleshed out.

I'm still not 100% comfortable with the arrow functions or promises, so I have a feeling some of the examples are redundant (the `err` handling in particular).

**Comment by CrabDude** [comment]
Cool, let me know when you're done and I'll take a look. In general, I'm
skipping callback examples in the code.

**Comment by psvet** [comment]
https://github.com/codepath/nodejs_guides/wiki/Filesystem

Updated. I removed callback examples from everything but the streams (creating and reading files) and `fs.watch`/`chokidar`—still working on figuring those out with promises.

**Comment by CrabDude** [comment]
Thanks.

**Comment by CrabDude** [comment]
Updated to assume pomises + `async/await`. `fs.watch` and `chokidar` use EventEmitter not node backs, so promises don't apply. Thanks for all your hard work!
