### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by CrabDude** [codepath/nodejs_guides#6]
- Round out the existing [CLI](https://github.com/codepath/nodejs_guides/wiki/CLI) with all the necessary information to complete the prework
- Include a shoutout to commander as more popular and more feature-filled and it's [variadic argument](https://www.npmjs.com/package/commander#variadic-arguments) support

**What success looks like: Succinctness and clarity. Less is more.**
Reference Wikis: [Authentication & Authorization](https://github.com/codepath/nodejs_guides/wiki/Authorization-&-Authentication), [Setup](https://github.com/codepath/nodejs_guides/wiki/Setup)

Open separate issues for required links to community sources if you're having trouble finding any.

_Please assign to yourself before working on this._
/cc @NinjaSudo @philster @azoff @DiyahM

**Comment by DiyahM** [comment]
This task mentions adding necessary information to complete the prework. Where's the prework located?

**Comment by nesquena** [comment]
http://courses.codepath.com/snippets/intro_to_nodejs/prework @DiyahM

**Comment by nesquena** [comment]
Here’s the prework: https://github.com/codepath/courses_content/blob/master/intro_to_nodejs/snippets/prework.md

--  
Nathan Esquenazi

**Comment by DiyahM** [comment]
The CLI guide appears to be pretty complete to support the prework. Let me know if there are more sections that I should add. 

In the meantime, I added a section on commander. Not sure how much detail to add. Can you check it out and let me know if more detail is needed? https://github.com/codepath/nodejs_guides/wiki/CLI

**Comment by CrabDude** [comment]
It should have examples. One really complex one that would be difficult or
impossible to do with yargs (e.g., variadic parameters) would suffice.

**Comment by DiyahM** [comment]
I've added some commander examples. Can you review and let me know if other changes should be made? https://github.com/codepath/nodejs_guides/wiki/CLI

**Comment by CrabDude** [comment]
LGTM. @DiyahM Thanks for the contributions!
