### ISSUE TITLE
Babel

### ISSUE THREAD

**Issue by CrabDude** [codepath/nodejs_guides#8]
- Explain reason for using babel (it'll all be in V8 soon and eventually won't need it at all)
- Glean relevant information from setup guide for getting up and running
- Show how to run your server
- explain the difference between babel & babel-node
- Show how to compile to a dist directory and run the compiled server
- explain/list common transforms & show how to set them in CLI & babelrc

**What success looks like: Succinctness and clarity. Less is more.**
Reference Wikis: [Authentication & Authorization](https://github.com/codepath/nodejs_guides/wiki/Authorization-&-Authentication), [Setup](https://github.com/codepath/nodejs_guides/wiki/Setup)

Open separate issues for required links to community sources if you're having trouble finding any.

_Please assign to yourself before working on this._
/cc @NinjaSudo @philster @azoff @DiyahM

**Comment by psvet** [comment]
https://github.com/codepath/nodejs_guides/wiki/Babel

/cc @CrabDude

**Comment by CrabDude** [comment]
LGTM. Edited. Thanks!
