### ISSUE TITLE
Modules & Packages

### ISSUE THREAD

**Issue by CrabDude** [codepath/nodejs_guides#9]
- Give code examples of building a module (module.exports)
- Add disclaimer to user `module.exports` not `exports`
- Link to docs and include resolution pattern of require path (e.g. core, path & installed)
- Explain node_modules
- Explain package.json dependencies
- Show how to install & rm packages with versions & --save
- Explain the difference between global and local packages
- Show where to search for packages  http://npmjs.com
- Explain semver [with link](http://semver.org) and semver ranges (e.g., `^` & `~`) and that ^ is default
- Link to package.json
- Explain package.json highlights

**What success looks like: Succinctness and clarity. Less is more.**
Reference Wikis: [Authentication & Authorization](https://github.com/codepath/nodejs_guides/wiki/Authorization-&-Authentication), [Setup](https://github.com/codepath/nodejs_guides/wiki/Setup)

Open separate issues for required links to community sources if you're having trouble finding any.

_Please assign to yourself before working on this._
/cc @NinjaSudo @philster @azoff @DiyahM

**Comment by psvet** [comment]
I just added this page to the wiki: https://github.com/codepath/nodejs_guides/wiki/Modules-&-Packages. Let me know of any changes that should be made. :+1:

**Comment by CrabDude** [comment]
Awesome. Thanks! I'll take a look and almost certainly make some changes.
Don't take it personally.

**Comment by CrabDude** [comment]
Updated. https://github.com/codepath/nodejs_guides/wiki/Modules-&-Packages
Thanks for all the hard work. This was good stuff. Try to be more concise
(terse) with the language.

**Comment by psvet** [comment]
Understood. I like the changes you made, and I'll try to make my next work more like that.
